#!/usr/bin/env python
# encoding: utf-8
"""
Run installer.
"""

from os import environ
from os.path import dirname, join, realpath
from subprocess import call


def _main():
    dotfiles_dir = realpath(dirname(__file__))

    # 'install' submodules
    call(';'.join([
        'cd ' + dotfiles_dir,
        'git submodule init',
        'git submodule update'
    ]), shell=True)

    # run installer
    installer = join(dotfiles_dir, 'installer/installer.py')
    call('python ' + installer, shell=True)

    # tell how to switch to zsh
    shell = environ.get('SHELL')
    if not shell or not shell.endswith('zsh'):
        print 'switch to zsh (you may need to relog): ' \
              'chsh -s `which zsh` $USER'

if __name__ == '__main__':
    _main()
