#!/usr/bin/env sh

# copied from:
#  -  https://github.com/mathiasbynens/dotfiles
#  -  https://github.com/inky/dotfiles
#  -  http://apple.stackexchange.com/questions/19468/suit-up


# Enable full keyboard access for all controls (e.g. enable Tab in modal
# dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Make Dock icons of hidden applications translucent
defaults write com.apple.dock showhidden -bool true

# Display full POSIX path as Finder window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# Allow quitting Finder via ⌘ + Q; doing so will also hide desktop icons
defaults write com.apple.finder QuitMenuItem -bool true

# Reset Dock and Finder
rm ~/Library/Application\ Support/Dock/*.db
for app in Dock Finder; do killall "$app"; done
